# Common
NAME = "name"

# Businesses search
BUSINESSES = "businesses"
ID = "id"
ALIAS = "alias"
IMAGE_URL = "image_url"
IS_CLOSED = "is_closed"
URL = "url"
REVIEW_COUNT = "review_count"
CATEGORIES = "categories"
ALIAS = "alias"
TITLE = "title"
RATING = "rating"
COORDINATES = "coordinates"
LATITUDE = "latitude"
LONGITUDE = "longitude"

# Reviews
AGGREGATE_RATING = "aggregateRating"
REVIEW_COUNT = "reviewCount"
RATING_VALUE = "ratingValue"
REVIEW = "review"
REVIEW_RATING = "reviewRating"
DATE_PUBLISHED = "datePublished"
DESCRIPTION = "description"
AUTHOR = "author"
SERVES_CUISINE = "servesCuisine"
PRICE_RANGE = "priceRange"
ADDRESS = "address"
ADDRESS_LOCALITY = "addressLocality"
ADDRESS_REGION = "addressRegion"
STREET_ADDRESS = "streetAddress"
POSTAL_CODE = "postalCode"
ADDRESS_COUNTRY = "addressCountry"
IMAGE = "image"
TELEPHONE = "telephone"
